### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by nezix** [JoshuaSenouf/LumenEngine#1]
Built with VS2015 on Windows 10 with a 770 GTX and CUDA 8.0
Same with a Linux build on Ubuntu 16.04 
The scene is correctly loaded but the window shows nothing but a black screen and the UI:

![image](https://user-images.githubusercontent.com/9949327/28815293-2ff38e48-76a1-11e7-99ac-cfff4054a5a4.png)

**Comment by JoshuaSenouf** [comment]
Change the working directory to the root of the project, i.e. where ths
res, src etc directories are.
Beware however that the engine is behaving kinda badly under Linux at the
moment, sometimes working, sometimes a buggy mess will be onscreen...

**Comment by nezix** [comment]
Ok thank you.
On Windows, changing directory does not change the behaviour. I verify that the scene is correctly loaded by printing the number of spheres allocated.

**Comment by JoshuaSenouf** [comment]
Did CMake properly found every important CUDA paths ? I had this problem once, resulting in the same situation as you if I am not mistaken.

**Comment by nezix** [comment]
I think so : 

> -- Building for: Visual Studio 14 2015
> -- The C compiler identification is MSVC 19.0.24215.1
> -- The CXX compiler identification is MSVC 19.0.24215.1
> -- Check for working C compiler using: Visual Studio 14 2015
> -- Check for working C compiler using: Visual Studio 14 2015 -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working CXX compiler using: Visual Studio 14 2015
> -- Check for working CXX compiler using: Visual Studio 14 2015 -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for pthread.h
> -- Looking for pthread.h - not found
> -- Found Threads: TRUE
> -- Could NOT find Vulkan (missing:  VULKAN_LIBRARY VULKAN_INCLUDE_DIR)
> -- Using Win32 for window creation
> -- Using WGL for context creation
> -- Found CUDA: F:/Cuda (found version "8.0")
> -- Configuring done
> -- Generating done
> -- Build files have been written to: F:/Down/LumenEngine-cuda/build

**Comment by JoshuaSenouf** [comment]
Okay, I think I got it.
Using a GTX 770, your CUDA compute capability is 3.0. I am using a GTX 970, with compute capability 5.2, and it is possible that I am using features not available on older GPUs.

In the CMakeLists.txt file, try changing this line : 

` --std=c++11 -gencode arch=compute_52,code=sm_52 --compiler-options -fno-strict-aliasing --ptxas-options=-v -maxrregcount 20 --use_fast_math)`

in

` --std=c++11 -gencode arch=compute_30,code=sm_30 --compiler-options -fno-strict-aliasing --ptxas-options=-v -maxrregcount 20 --use_fast_math)`

Know that doing this will result in the same black screen as you in my case, but that might be because you need to put the exact compute capability of your GPU. Can't hurt to try.

**Comment by nezix** [comment]
That's it !
Thank you so much for your support and this nice work !
